### ISSUE TITLE
bug: AARCH64 not correct process VFP  

### ISSUE THREAD

**Issue by guoweikang** [Starry-OS/Starry#16]
AARCH64  动态库用例失败

郑友捷：
 - 原先的aarch64测例问题来自于fp_simd
 
![4f412f78afe94d84db261f9f8cd7ee9](https://github.com/user-attachments/assets/011623cd-cb9d-47de-a6f7-fb5a2ee72103)

Starry 在https://github.com/Starry-OS/Starry/commit/65a4f5896317115cf1edc74800f0da5d92923243这次更新中将启用 fp_simd 时的平台更改为 aarch64-unknown-none，原先是aarch64-unknown-none-softfloat，然后导致运行到 memset 的时候 q0 的值发生了变化

![acda1e3e342d40dc1397132b9b4f83e](https://github.com/user-attachments/assets/8b970162-85c2-46bd-b2a1-3b9b4e2f8656)

但是如果我打开了fp_simd，同时指定了TARGET := aarch64-unknown-none-softfloat，会报这个错误

**Comment by guoweikang** [comment]
此问题在更新升级工具链以后出现的问题  
- 工具链升级之前，编译内核支持 `-neon` (生成代码不适用VFP寄存器)， 并且就算代码中有显示使用VFP的汇编，在编译链接时没有报错 
- 工具链升级之后，编译内核支持 `-neon` (生成代码不适用VFP寄存器)， 但是代码中有显示使用VFP的汇编，在编译链接时会报错 

解决方案:  尝试搜索过cargo 支持不同target构建  方案不适合我们场景，

建议方案： VFP.S 作为独立的汇编文件，在`buidl.rs`中编译，同时在链接时 在`build.rs` 单独链接， 不能和其他rust 项目在链接在一起

**Comment by Azure-stars** [comment]
涉及 PR：
- Starry-OS/taskctx#3
- Starry-OS/Starry#17
