### ISSUE TITLE
preempt is necessary for run_static.sh testcases, but fat32 doesn't support multi thread 

### ISSUE THREAD

**Issue by li041** [Starry-OS/Starry#22]
- run_static.sh测例会在用户态死循环, 需要内核抢占, FEATURES=sched_rr或sched_cfs启用
- 开启任务抢占后, iozone目前在fat32文件系统下会panic, 原因是目前fat32不支持多线程, 在发生任务抢占后, 会导致`BorrowMut` panic

**Comment by Azure-stars** [comment]
Now the CI will run the libc-test with sched_rr feature.
