### ISSUE TITLE
TCP 支持 `SO_REUSEADDR`选项

### ISSUE THREAD

**Issue by Azure-stars** [Starry-OS/Starry#9]
`SO_REUSEADDR` 选项有以下几个作用：

1. **允许端口重用**：当一个 TCP 连接关闭后，连接的端口会进入 `TIME_WAIT` 状态，此时端口虽然没有被使用，但仍然不能立即重新绑定。启用 `SO_REUSEADDR` 选项后，可以在该端口仍处于 `TIME_WAIT` 状态时，重新绑定该端口。
2. **允许多个套接字绑定到同一个端口**：在某些多播协议的应用中，多个套接字可以绑定到同一个端口，使用 `SO_REUSEADDR` 可以实现这一点。
3. **解决服务器重启绑定端口的问题**：在服务器程序重启时，如果上一次运行的服务器占用了某个端口且该端口尚未完全释放，启用 `SO_REUSEADDR` 选项可以让新启动的服务器成功绑定到同一个端口。

之前在 UDP 上支持了 `SO_REUSEADDR`，见该 PR：https://github.com/Arceos-monolithic/Starry/pull/37/files，可以用作 TCP 支持 `SO_REUSEADDR` 参考。

测试方式：可以根据第一和二个点设计测例，将多个套接字绑定到同一个端口，或者重用一个端口。

**Comment by Josen-B** [comment]
涉及PR:
- https://github.com/Starry-OS/linux_syscall_api/pull/14
- https://github.com/Starry-OS/axnet/pull/2
- https://github.com/rcore-os/smoltcp/pull/2
- https://github.com/Starry-OS/testcases/pull/5
